name: Update workflow
on:
  push:
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Updating
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /pub/fgovir/cmsc389T-web
            git pull
